# Site settings
title: Expeditio Dev Blog
description: Follow the development of the open world roguelike Expeditio!
baseurl: ""
url: "https://blog.auriosi.xyz"
permalink: /:year/:month/:day/:title/
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
