# Site settings
title: Expeditio Dev Blog
description: Follow the development of the open world roguelike Expeditio!
baseurl: ""
url: "https://blog.auriosi.xyz"
permalink: /:categories/:year/:month/:day/:title/
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
